name = "free-tailwind-admin-dashboard-template"
compatibility_date = "2026-09-17"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "MI_BASE_DE_DATOS"
database_name = "uniminuto"
database_id = "dd18142e-baf0-4a5e-bfaf-f9a358d030b7"